name: Swift

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  doc:
    name: Generate Documentation
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fwal/setup-swift@v1
        with:
          swift-version: "5.7"
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "14"
      - name: Build
        run: swift package generate-documentation --target SwiftAirmen
